import os
from typing import Dict, List, Optional

import requests


class FacebookGraphAPIError(RuntimeError):
    pass


class FacebookGraphClient:
    """
    Low-level Meta Graph API client for Facebook Page publishing and organic results collection.

    Publishing uses Page endpoints; results collection fetches object details and post insights.
    """

    POST_OBJECT_FIELDS = (
        "id,created_time,permalink_url,shares,"
        "comments.summary(true),likes.summary(true)"
    )
    PHOTO_OBJECT_FIELDS = (
        "id,created_time,link,page_story_id,"
        "comments.summary(true),likes.summary(true)"
    )

    # Meta's v25.0 Page Insights update replaces legacy impressions/reach post metrics
    # with media-view based metrics. Keep both modern and legacy profiles so older pinned
    # Graph API versions can still work where they remain supported.
    MODERN_POST_INSIGHT_METRICS = [
        "post_media_view",
        "post_total_media_view_unique",
        "post_clicks",
    ]
    LEGACY_POST_INSIGHT_METRICS = [
        "post_impressions",
        "post_impressions_unique",
        "post_clicks",
    ]

    def __init__(
        self,
        page_id: Optional[str] = None,
        page_access_token: Optional[str] = None,
        graph_version: Optional[str] = None,
        timeout: Optional[int] = None,
    ):
        self.page_id = page_id or os.getenv("META_PAGE_ID")
        self.page_access_token = page_access_token or os.getenv("META_PAGE_ACCESS_TOKEN")
        self.graph_version = graph_version or os.getenv("META_GRAPH_VERSION", "v25.0")
        self.timeout = int(timeout or os.getenv("FACEBOOK_PUBLISH_TIMEOUT", "30"))

    def _base_url(self, endpoint: str) -> str:
        if endpoint.startswith("/"):
            endpoint = endpoint[1:]
        return f"https://graph.facebook.com/{self.graph_version}/{endpoint}"

    def _require_auth(self, require_page_id: bool = False):
        if require_page_id and not self.page_id:
            raise ValueError("META_PAGE_ID is required.")
        if not self.page_access_token:
            raise ValueError("META_PAGE_ACCESS_TOKEN is required.")

    def _request(self, method: str, endpoint: str, data: Dict, require_page_id: bool = False) -> Dict:
        self._require_auth(require_page_id=require_page_id)

        payload = dict(data or {})
        payload["access_token"] = self.page_access_token
        method = method.upper()

        kwargs = {
            "method": method,
            "url": self._base_url(endpoint),
            "timeout": self.timeout,
        }
        if method == "GET":
            kwargs["params"] = payload
        else:
            kwargs["data"] = payload

        response = requests.request(**kwargs)

        try:
            body = response.json()
        except Exception:
            body = {"raw_text": response.text}

        if not response.ok:
            raise FacebookGraphAPIError(
                f"Graph API error {response.status_code}: {body}"
            )

        return body

    def schedule_feed_post(self, message: str, scheduled_publish_time: int) -> Dict:
        endpoint = f"{self.page_id}/feed"
        payload = {
            "message": message,
            "published": "false",
            "scheduled_publish_time": scheduled_publish_time,
        }
        return self._request("POST", endpoint, payload, require_page_id=True)

    def schedule_photo_post(self, caption: str, image_url: str, scheduled_publish_time: int) -> Dict:
        endpoint = f"{self.page_id}/photos"
        payload = {
            "url": image_url,
            "caption": caption,
            "published": "false",
            "scheduled_publish_time": scheduled_publish_time,
        }
        return self._request("POST", endpoint, payload, require_page_id=True)

    def get_object(self, object_id: str, fields: str) -> Dict:
        return self._request("GET", object_id, {"fields": fields})

    def get_content_details(self, object_id: str) -> Dict:
        """
        Read a Facebook object generated by the scheduler.

        Text/feed scheduling normally returns a Post object. Photo scheduling often returns a Photo object.
        These object types expose different fields, so we try Post fields first, then Photo fields.

        For published Page photos, `page_story_id` is the related Page Post. We use that Page Post as the
        source of truth for:
        - permalink URL (`post_url` in Organic_Results)
        - shares/likes/comments for the post story
        - post insights object id
        """
        errors = []
        try:
            data = self.get_object(object_id, self.POST_OBJECT_FIELDS)
            data["_collector_object_type"] = "post"
            data["_insights_object_id"] = object_id
            return data
        except Exception as exc:
            errors.append(f"post_fields: {exc}")

        try:
            photo_data = self.get_object(object_id, self.PHOTO_OBJECT_FIELDS)
            photo_data["_collector_object_type"] = "photo"
            photo_data["_photo_object_id"] = object_id
            photo_data["_insights_object_id"] = object_id

            page_story_id = str(photo_data.get("page_story_id") or "").strip()
            if page_story_id:
                photo_data["_page_story_id"] = page_story_id
                photo_data["_insights_object_id"] = page_story_id
                try:
                    page_post = self.get_object(page_story_id, self.POST_OBJECT_FIELDS)
                    photo_data["_related_page_post"] = page_post
                    # Use the Page Post fields as the canonical post-level values.
                    if page_post.get("permalink_url"):
                        photo_data["permalink_url"] = page_post.get("permalink_url")
                    if page_post.get("shares") is not None:
                        photo_data["shares"] = page_post.get("shares")
                    if page_post.get("likes") is not None:
                        photo_data["likes"] = page_post.get("likes")
                    if page_post.get("comments") is not None:
                        photo_data["comments"] = page_post.get("comments")
                    if page_post.get("created_time"):
                        photo_data["created_time"] = page_post.get("created_time")
                except Exception as exc:
                    photo_data["_page_story_fetch_error"] = str(exc)
            return photo_data
        except Exception as exc:
            errors.append(f"photo_fields: {exc}")

        raise FacebookGraphAPIError(
            "Unable to fetch Facebook content details using Post or Photo fields. "
            + " | ".join(errors)
        )

    def _request_insights_batch(self, object_id: str, metric_names: List[str], profile_name: str) -> Dict:
        payload = self._request(
            "GET",
            f"{object_id}/insights",
            {
                "metric": ",".join(metric_names),
                "period": "lifetime",
            },
        )
        payload["_metric_profile"] = profile_name
        payload["_metric_request_mode"] = "batch"
        return payload

    def _request_insights_individual(self, object_id: str, metric_names: List[str], profile_name: str) -> Dict:
        merged = []
        errors = []
        for metric_name in metric_names:
            try:
                payload = self._request(
                    "GET",
                    f"{object_id}/insights/{metric_name}",
                    {"period": "lifetime"},
                )
                merged.extend(payload.get("data", []) or [])
            except Exception as exc:
                errors.append(f"{metric_name}: {exc}")
        if not merged:
            raise FacebookGraphAPIError(
                f"No {profile_name} insight metrics returned via individual endpoints. "
                + " | ".join(errors)
            )
        return {
            "data": merged,
            "_metric_profile": profile_name,
            "_metric_request_mode": "individual",
            "_metric_errors": errors,
        }

    def get_post_insights(self, object_id: str) -> Dict:
        """
        Fetch Facebook Page Post insights as robustly as possible.

        Order of attempts:
        1. Modern v25+ metric profile, batch request.
        2. Modern v25+ metric profile, one metric endpoint at a time.
        3. Legacy pre-v25 metric profile, batch request.
        4. Legacy pre-v25 metric profile, one metric endpoint at a time.
        """
        errors = []
        attempts = [
            (self.MODERN_POST_INSIGHT_METRICS, "modern", "batch"),
            (self.MODERN_POST_INSIGHT_METRICS, "modern", "individual"),
            (self.LEGACY_POST_INSIGHT_METRICS, "legacy", "batch"),
            (self.LEGACY_POST_INSIGHT_METRICS, "legacy", "individual"),
        ]
        for metric_names, profile_name, mode in attempts:
            try:
                if mode == "batch":
                    return self._request_insights_batch(object_id, metric_names, profile_name)
                return self._request_insights_individual(object_id, metric_names, profile_name)
            except Exception as exc:
                errors.append(f"{profile_name}/{mode}: {exc}")
        raise FacebookGraphAPIError(
            "Unable to fetch Facebook post insights with modern or legacy metrics. "
            + " | ".join(errors)
        )

    def delete_object(self, object_id: str) -> Dict:
        return self._request("DELETE", object_id, {})
