PAGE_CHANNEL_LIBRARY_TIMEFRAME_COLUMNS_V7 = [
    "start_day",
    "end_day",
    "duration",
]

PAGE_CHANNEL_LIBRARY_HEADERS_V7 = [
    "public_page_id",
    "private_page_id",
    "token",
    "brand_id",
    "niche_id",
    "platform_id",
    "page_name",
    "page_url",
    "market",
    "language",
    "target_timezone",
    "page_stage",
    "current_followers",
    "current_likes",
    "target_followers",
    "target_likes",
    "primary_growth_metric",
    "growth_goal",
    "start_day",
    "end_day",
    "duration",
    "default_content_goal",
    "campaign_macro_direction",
    "default_tone",
    "default_product_mention_level",
    "posting_frequency_target",
    "status",
    "notes",
]
